### ISSUE TITLE
connot find libfst.so.10

### ISSUE THREAD

**Issue by xiechen0692** [mathquis/node-kaldi-online-nnet3-decoder#1]
```
internal/modules/cjs/loader.js:1021
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: libfst.so.10: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1021:18)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/classiii/Downloads/node-kaldi-online-nnet3-decoder-master/lib/index.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
```

Hi! Thanks for answering me at kaldi-node. 
I have changed the path in the binding.gyp. As followed:

```
{
  "targets": [
    {
      "target_name": "kaldi",
      "cflags!": [ "-fno-exceptions" ],
      "cflags_cc!": [ "-fno-exceptions" ],
      "sources": [
        "./src/nnet3.cpp"
      ],
      "include_dirs": [
        "<!@(node -p \"require('node-addon-api').include\")",
        "/home/classiii/kaldi/src",
        "/home/classiii/kaldi/tools/openfst-1.6.7/include"
      ],
      "ldflags": [
        "-rdynamic",
        "-ldl",
        "-lm",
        "-lpthread"
      ],
      "cflags_cc": [
        "-std=c++11",
        "-Wall",
        "-Wno-sign-compare",
        "-Wno-unused-local-typedefs",
        "-Wno-deprecated-declarations",
        "-Winit-self",
        "-DKALDI_DOUBLEPRECISION=0",
        "-DHAVE_EXECINFO_H=1",
        "-DHAVE_CXXABI_H",
        "-DHAVE_ATLAS",
        "-m64",
        "-msse",
        "-msse2",
        "-pthread",
        "-g",
        "-fPIC",
        "-frtti"
      ],
      "library_dirs": [
        "/usr/lib",
        "/home/classiii/kaldi/tools/openfst-1.6.7/lib",
        "/home/classiii/kaldi/src/base",
        "/home/classiii/kaldi/src/chain",
        "/home/classiii/kaldi/src/cudamatrix",
        "/home/classiii/kaldi/src/decoder",
        "/home/classiii/kaldi/src/feat",
        "/home/classiii/kaldi/src/fstext",
        "/home/classiii/kaldi/src/gmm",
        "/home/classiii/kaldi/src/hmm",
        "/home/classiii/kaldi/src/ivector",
        "/home/classiii/kaldi/src/lat",
        "/home/classiii/kaldi/src/lm",
        "/home/classiii/kaldi/src/matrix",
        "/home/classiii/kaldi/src/nnet2",
        "/home/classiii/kaldi/src/nnet3",
        "/home/classiii/kaldi/src/online2",
        "/home/classiii/kaldi/src/transform",
        "/home/classiii/kaldi/src/tree",
        "/home/classiii/kaldi/src/util"
      ],
      "libraries": [
        "-latlas",
        "-lfst",
        "-lkaldi-online2",
        "-lkaldi-ivector",
        "-lkaldi-nnet3",
        "-lkaldi-chain",
        "-lkaldi-nnet2",
        "-lkaldi-cudamatrix",
        "-lkaldi-decoder",
        "-lkaldi-lat",
        "-lkaldi-fstext",
        "-lkaldi-hmm",
        "-lkaldi-feat",
        "-lkaldi-transform",
        "-lkaldi-gmm",
        "-lkaldi-tree",
        "-lkaldi-util",
        "-lkaldi-matrix",
        "-lkaldi-base",
      ],
      'defines': [ 'NAPI_DISABLE_CPP_EXCEPTIONS' ],
    }
  ]
}
```

**There are not any errors when in "npm install".
I also can find libfst.so.10 in the path of "openfst-1.6.7/lib"
I dont know where I setting wrong, can you help me solve that?
thank you so much.**

**Comment by mathquis** [comment]
I would try to add the path to libfst.10.so to ldconfig:
`echo "/opt/kaldi/tools/openfst-1.6.7/lib" >> /etc/ld.so.conf && ldconfig`

Maybe do the same for all the other libs if required.

**Comment by xiechen0692** [comment]
Thanks! I solved the problem above.
But here is a new question, did you meet before?
```
-decoder-master$ node test.js 61-70968-0001.wav 
EndpointRule {}
EndpointRule {}
EndpointRule {}
EndpointRule {}
EndpointRule {}
LOG ([5.5.677~1-99d1]:OnlineNNet3Model():src/nnet3.cpp:79) Loading feature configuration...
LOG ([5.5.677~1-99d1]:OnlineNNet3Model():src/nnet3.cpp:103) Loading decodable configuration...
LOG ([5.5.677~1-99d1]:OnlineNNet3Model():src/nnet3.cpp:118) Loading acoustic model: ./resources/model/final.mdl
node: symbol lookup error: /opt/intel/mkl/lib/intel64/libmkl_vml_avx2.so: undefined symbol: mkl_serv_getenv
```

**Comment by mathquis** [comment]
It looks like your Kaldi libraries were compiled using IntelMKL instead of ATLAS.

At least 2 options:
- Preload the IntelMKL libraries using LD_PRELOAD
- Compile the Kaldi libraries using ATLAS instead (something like `./configure --shared --mathlib=ATLAS` in `/kaldi/src` dir)

Note there may also be other alternatives :)

Hope this helps.

**Comment by mathquis** [comment]
@xiechen0692 Did you manage to make it work? Can I close this issue?
